const historicalFacts = [
    `Napoleon was once attacked by a horde of bunnies. He had ordered a rabbit hunt, but they turned on him instead.`,
    `Albert Einstein’s brain was stolen after his death, but it was eventually returned... for science.`,
    `Cleopatra lived closer in time to the first Moon landing than to the construction of the Great Pyramid of Giza.`,
    `Before alarm clocks, people were hired as ‘knocker-uppers’ to shoot peas at windows to wake people up.`,
    `The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.`,
    `Winston Churchill was hit by a car on Fifth Avenue in New York. His response? ‘I should have looked both ways.’`,
    `Roman Emperor Caligula declared war on Neptune, god of the sea, and commanded his soldiers to stab the ocean.`,
    `In 1923, jockey Frank Hayes won a horse race despite being dead. He had a heart attack mid-race but stayed on the horse.`,
    `In ancient Greece, throwing an apple at someone was considered a way to propose marriage.`,
    `President Andrew Jackson had a pet parrot who learned to curse so well that it had to be removed from his funeral.`,
    `In 1912, a French tailor named Franz Reichelt jumped off the Eiffel Tower wearing a homemade parachute. It didn’t work.`,
    `King Henry VIII had people who were paid to wipe his bottom. They were called ‘Grooms of the Stool.’`,
    `In 1838, the State of Missouri declared it legal to kill Mormons. It wasn’t repealed until 1976.`,
    `Otto the Great, a Holy Roman Emperor, wore his crown so often that people called him 'Otto the Crowned.'`,
    `In 1920, Babe Ruth outran a speeding train… well, at least for 100 yards until he collapsed from exhaustion.`,
    `In ancient Rome, some people believed that drinking gladiator blood could cure epilepsy.`,
    `Albert Einstein was offered the presidency of Israel in 1952, but he declined, saying he wasn’t good with people.`,
    `The first known contraceptive was crocodile dung used by ancient Egyptians.`,
    `The inventor of the Pringles can, Fred Baur, had his ashes buried in a Pringles can after he died.`,
    `In the 1800s, dentures were often made from the teeth of dead soldiers. These ‘Waterloo teeth’ were in high demand.`,
    `Peter the Great of Russia imposed a tax on beards in 1698 to promote Western grooming styles.`,
    `In 1374, an outbreak of ‘dancing plague’ in Europe caused people to dance uncontrollably for days until they collapsed.`,
    `The famous Viking, Erik the Red, was exiled from Iceland for murder and had to start a new life in Greenland.`,
    `French military leader Charles de Gaulle survived 31 assassination attempts.`,
    `The guillotine was still used in France up until 1977, the same year 'Star Wars' was released.`,
    `During WWII, British soldiers were taught to salute magpies because of a superstition that seeing just one was bad luck.`,
    `In 1820, the British navy banned sailors from wearing earrings… because they believed the earrings were hypnotizing them.`,
    `In 1917, the U.S. government jailed a man for teaching his dog to raise its paw like a Nazi salute.`,
    `Thomas Jefferson and John Adams both died on the same day—July 4, 1826, the 50th anniversary of the Declaration of Independence.`,
    `In 1518, there was a ‘Dancing Plague’ in Strasbourg where people literally danced until they died from exhaustion.`,
    `The oldest "Yo Mama" joke dates back to 3,500 years ago in ancient Babylon.`,
    `The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of the iron.`,
    `Ketchup was sold as medicine in the 1830s and was believed to cure ailments like indigestion.`,
    `Pope Gregory IX once declared that cats were associated with devil worship, which led to a large-scale killing of cats in Europe.`,
    `A rooster was the first passenger in a hot air balloon in 1783, along with a sheep and a duck.`,
    `Abraham Lincoln was a licensed bartender before becoming the 16th U.S. president.`,
    `Thomas Edison was afraid of the dark, even though he is famous for inventing the lightbulb.`,
    `King Tut’s parents were brother and sister. This is believed to have contributed to his early death due to genetic disorders.`,
    `The Leaning Tower of Pisa has been leaning for over 800 years, and it took 177 years to build.`,
    `Charlie Chaplin once entered a Chaplin lookalike contest and lost. He didn’t even make the finals!`,
    "In 1939, a group of scientists invented a new type of rubber that could withstand extreme temperatures. They called it 'Buna' and it was used in tires during WWII.",
    "The Great Wall of China is not a single wall but a series of walls and fortifications built over several dynasties, totaling more than 13,000 miles in length.",
    "In the 17th century, tulips became so valuable in the Netherlands that a single bulb could sell for more than a house, leading to 'Tulip Mania.'",
    "In 1975, a man named Paul McCartney was briefly detained in Japan for carrying marijuana; he was released and later apologized for his actions.",
    "The first known instance of a vending machine was in ancient Greece, where it dispensed holy water in exchange for coins.",
    "In 1825, the first public railway was opened in England, and it was powered by a locomotive named 'Locomotion No. 1.'",
    "The longest-running play in the world, 'The Mousetrap' by Agatha Christie, has been performed continuously since 1952 in London.",
    "In ancient Egypt, servants were smeared with honey to attract flies away from the pharaoh.",
    "In 1847, the first medical school for women in the U.S. was founded at the New England Female Medical College.",
    "In 1883, the eruption of Krakatoa was so powerful that it was heard 3,000 miles away, and it significantly affected global temperatures for years.",
    "The first known use of the word 'nerd' was in Dr. Seuss's 1950 book 'If I Ran the Zoo.'",
    "In 1969, the first human to walk on the Moon, Neil Armstrong, said, 'That's one small step for man, one giant leap for mankind.'",
    "The first computer programmer was Ada Lovelace, who wrote algorithms for Charles Babbage's early mechanical general-purpose computer in the 1840s.",
    "During World War II, the U.S. military developed a 'ghost army' of artists and designers to create inflatable tanks and sound effects to deceive the enemy.",
    "In 1927, a dog named 'Toto' from 'The Wizard of Oz' was valued at $125,000 by its owner, making it one of the most valuable pets at the time.",
    "The first known contraceptive method was using a mixture of honey and crocodile dung in ancient Egypt.",
    "In the 1800s, some doctors believed that smoking was beneficial for health, leading to widespread cigarette use.",
    "The first known video game, 'Tennis for Two,' was created in 1958 on an oscilloscope by physicist William Higinbotham.",
    "In ancient Rome, it was common for wealthy citizens to keep pet monkeys, which were often dressed in clothing.",
    "In 1967, the first-ever heart transplant was performed in South Africa by Dr. Christiaan Barnard, marking a significant milestone in medical history."
];

module.exports = { historicalFacts };